title: "Under Maintenance"
description: "This site is currently under maintenance."
minimal_mistakes_skin: contrast

search: false
search_full_content: false

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /

masthead_title: ""

include:
  - _pages

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author: {}
footer: {}

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false