title: "Under Maintenance"
description: "This site is currently under maintenance."

# disable theme features
search: false
paginate: 0

# basic build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# remove author / footer / extras
author: {}
footer: {}

# only include pages folder
include:
  - _pages

# plugins
plugins:
  - jekyll-include-cache

# default layout
defaults:
  - scope:
      path: ""
    values:
      layout: single